FROM   mcr.microsoft.com/dotnet/sdk:8.0 As build
WORKDIR /source
COPY *.csproj .
RUN dotnet restore
#publish
COPY . .
RUN dotnet publish -c release -o /app
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT [ "dotnet" ,"backend.api.dll"]
