FROM node:hydrogen-alpine3.20 AS build
RUN mkdir -p /app
WORKDIR /app
COPY package.json ./
RUN npm install --force
COPY . ./
RUN npm run build
FROM nginx:stable-alpine3.20-perl
COPY --from=build /app/dist/front/browser/ /usr/share/nginx/html
